version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: spendr-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spendr_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chromadb:
    image: chromadb/chroma:latest
    container_name: spendr-chroma
    restart: always
    ports:
      - "8000:8000"

volumes:
  pgdata:
